{-
   Lethean Binary API
   Functionality to simplify using LTHN

   The version of the OpenAPI document: 1.2.2
   Contact: contact@lethean.io

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Vpn exposing
    ( startLetheand
    )

import Api
import Api.Data
import Dict
import Http
import Json.Decode
import Json.Encode



startLetheand : String -> Maybe Bool -> Api.Request ()
startLetheand dataDir_query version_query =
    Api.request
        "GET"
        "/letheand/start"
        []
        [ ( "version", Maybe.map (\val -> if val then "true" else "false") version_query ), ( "data_dir", Just <| identity dataDir_query ) ]
        []
        Nothing
        (Json.Decode.succeed ())
